# Generated by Django 3.1 on 2020-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0002_auto_20200920_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captures',
            fields=[
                ('face', models.BinaryField()),
                ('employee_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'capture',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
