# Generated by Django 3.1 on 2020-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0004_auto_20200920_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nowcapture',
            fields=[
                ('nowtime', models.DateTimeField(db_column='NowTime', primary_key=True, serialize=False)),
                ('nowcapture', models.TextField(db_column='NowCapture')),
                ('nowpeople', models.CharField(db_column='NowPeople', max_length=45)),
            ],
            options={
                'db_table': 'nowcapture',
                'managed': False,
            },
        ),
    ]
