# Generated by Django 3.1 on 2020-10-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0005_nowcapture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nowcapture',
        ),
    ]
