# Generated by Django 3.1 on 2020-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PersonFace',
            field=models.ImageField(upload_to='capture/'),
        ),
    ]
