# Generated by Django 3.1 on 2020-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200907_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('face', models.CharField(max_length=60)),
                ('employee_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'capture',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
