# Generated by Django 3.1 on 2020-09-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200907_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
